[QLineEdit]
cursorPositionChanged = ["int", "int"]
editingFinished = []
inputRejected = []
returnPressed = []
selectionChanged = []
textChanged = ["str"]
textEdited = ["str"]

[QAction]
changed = []
hovered = []
toggled = ["bool"]
triggered = []

[QPushButton]
clicked = []
toggled = ["bool"]
pressed = []
released = []

[QRadioButton]
clicked = []
toggled = ["bool"]
pressed = []
released = []

[QCheckBox]
clicked = []
toggled = ["bool"]
pressed = []
released = []

[QToolButton]
clicked = []
toggled = ["bool"]
pressed = []
released = []
triggered = []  # this might have a QAction